<a href="https://colab.research.google.com/github/awatson1022/Kaggle-MNIST-Digit-Recognition-Competition/blob/main/Watson_Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I apply Tensor Flow neural networks to predict the MNIST digit labels for the Kaggle Digit Recognizer Competition. Additionally, I alter the number of layers and nodes to evaluate their impact on prediction accuracy.

# Ingestion

In [ ]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [ ]:
df = pd.read_csv("digit_train.csv") #import train df from Kaggle

In [ ]:
df.head()

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [ ]:
df2 = pd.read_csv("digit_test.csv") #import test df from Kaggle

In [ ]:
df2.head()

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0       0       0       0  ...         0         0         0         0
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...         0         0         0         0
3       0       0       0       0  ...         0         0         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]

In [ ]:
train_images = df.drop('label', axis=1) #create train data
train_labels = df[['label']]
train_images = train_images.astype('int32')
train_labels = train_labels.astype('int32')

In [ ]:
test_images = df2 #create test data
test_images = test_images.astype('int32')

In [ ]:
train_images.head()

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0       0       0       0  ...         0         0         0         0
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...         0         0         0         0
3       0       0       0       0  ...         0         0         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]

In [ ]:
train_labels.head()

label
0      1
1      0
2      1
3      4
4      0

In [ ]:
test_images.head()

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0       0       0       0  ...         0         0         0         0
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...         0         0         0         0
3       0       0       0       0  ...         0         0         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]

# EDA

There are 42,000 train images with 784 pixels.

In [ ]:
train_images.shape 

(42000, 784)

There are 42,000 train labels to match the train images.

In [ ]:
len(train_labels)

42000

The labels are integers 0-9.

In [ ]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

There are 28,000 test images with 784 pixels. This makes a 60/40 train-test splt.

In [ ]:
test_images.shape

(28000, 784)

# Tensor Flow Test 1

I rewrite the data as arrays and scale the images before fitting the model. 

In [ ]:
train_images = np.array(train_images) #Rewrite train_images df as array
train_images

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [ ]:
train_labels = np.array(train_labels) #Rewrite train_labels df as array
train_labels

array([[1],
       [0],
       [1],
       ...,
       [7],
       [6],
       [9]], dtype=int32)

In [ ]:
test_images = np.array(test_images) #Rewrite test_images df as array
test_images

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [ ]:
train_images = train_images / 255.0 #Scale the data by dividing by the max pixel value(255) to obtain values between 0-1
test_images = test_images / 255.0

For my original model, I want to use 2 layers with 10 nodes per layer. 

In [ ]:
model1 = tf.keras.Sequential([                    #Set model hyperparameters
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10)
    ])

In [ ]:
model1.compile(optimizer='adam',        #Compile the model
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model1.fit(train_images, train_labels, epochs=10) #Fit the model with the training data

Epoch 1/10
1313/1313 [==============================] - 2s 1ms/step - loss: 1.0646 - accuracy: 0.6781
Epoch 2/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.3360 - accuracy: 0.9048
Epoch 3/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2885 - accuracy: 0.9168
Epoch 4/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.2606 - accuracy: 0.9244
Epoch 5/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.2497 - accuracy: 0.9274
Epoch 6/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2419 - accuracy: 0.9286
Epoch 7/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2287 - accuracy: 0.9354
Epoch 8/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.2268 - accuracy: 0.9344
Epoch 9/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2226 - accuracy: 0.9365
Epoch 10/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.216

I evaluate the training set accuracy. The model uses 1 second of processing time with an accuracy of 0.9404.

In [ ]:
model1.evaluate(train_images, train_labels)

1313/1313 [==============================] - 1s 987us/step - loss: 0.2078 - accuracy: 0.9404


[0.20780156552791595, 0.9404285550117493]

I apply a softmax layer to obtain prediction probabilities with the test data for each possible label.

In [ ]:
probability_model1 = tf.keras.Sequential([model1, 
                                         tf.keras.layers.Softmax()]) #Apply softmax

In [ ]:
predictions1 = probability_model1.predict(test_images) #Use the fitted model obtain test predictions

In [ ]:
predictions1[0] #The predictions are probabilities for each possible label

array([1.3921595e-05, 2.3963958e-15, 9.9998426e-01, 1.5141155e-06,
       2.9960905e-16, 5.7899370e-09, 3.5971730e-09, 3.9071697e-08,
       2.2546458e-07, 2.2971090e-11], dtype=float32)

I can use argmax to identify the most likely label based on the probabilities.

In [ ]:
np.argmax(predictions1[0])

2

I generate list of test data predictions and write a CSV for Kaggle submission.

In [ ]:
index_array1 = np.argmax(predictions1, axis=-1) #I obtain my predictions in the form of an array
index_array1

array([2, 0, 9, ..., 3, 9, 2])

In [ ]:
tfpred1 = pd.DataFrame(index=df2.index) #I create a df with predictions and format for Kaggle submission
tfpred1['ImageId'] = tfpred1.index
tfpred1['ImageId'] += 1
tfpred1['Label'] = index_array1
tfpred1

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      7
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [ ]:
tfpred1.to_csv(r'C:\Users\Andrew\Desktop\tfpred1.csv', index = False, header=True) #I write a CSV with predictions and submit to Kaggle

The Kaggle submission receives a score of 0.92685 accuracy.

# Tensor Flow Test 2

For my second model, I want to use 2 layers with 20 nodes per layer. 

In [ ]:
model2 = tf.keras.Sequential([                #Set model hyperparameters
    tf.keras.layers.Dense(20, activation='relu'),
    tf.keras.layers.Dense(20)
    ])

In [ ]:
model2.compile(optimizer='adam',                  #Optimize model
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model2.fit(train_images, train_labels, epochs=10)   #Train model

Epoch 1/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.9151 - accuracy: 0.7521
Epoch 2/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.2873 - accuracy: 0.9174
Epoch 3/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.2361 - accuracy: 0.9333
Epoch 4/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.2197 - accuracy: 0.9391
Epoch 5/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.1957 - accuracy: 0.9457
Epoch 6/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.1724 - accuracy: 0.9520
Epoch 7/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.1602 - accuracy: 0.9553
Epoch 8/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.1535 - accuracy: 0.9561
Epoch 9/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.1372 - accuracy: 0.9617
Epoch 10/10
1313/1313 [==============================] - 2s 1ms/step - loss: 0.133

I evaluate the training set accuracy. The model uses 1 second of processing time with an accuracy of 0.9661.

In [ ]:
model2.evaluate(train_images, train_labels)

1313/1313 [==============================] - 1s 1ms/step - loss: 0.1164 - accuracy: 0.9661


[0.11643814295530319, 0.9661190509796143]

In [ ]:
probability_model2 = tf.keras.Sequential([model2,       #Apply softmax layer
                                         tf.keras.layers.Softmax()])

In [ ]:
predictions2 = probability_model2.predict(test_images)    #Generate test predictions

In [ ]:
index_array2 = np.argmax(predictions2, axis=-1) #I obtain my predictions in the form of an array
index_array2

array([2, 0, 9, ..., 3, 9, 2])

In [ ]:
tfpred2 = pd.DataFrame(index=df2.index) #I create a df with predictions and format for Kaggle submission
tfpred2['ImageId'] = tfpred2.index
tfpred2['ImageId'] += 1
tfpred2['Label'] = index_array2
tfpred2

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      4
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [ ]:
tfpred2.to_csv(r'C:\Users\Andrew\Desktop\tfpred2.csv', index = False, header=True) #I write a CSV with predictions and submit to Kaggle

The Kaggle submission receives a score of 0.94989 accuracy.

# Tensor Flow Test 3

For my third model, I want to use 5 layers with 10 nodes per layer. 

In [ ]:
model3 = tf.keras.Sequential([        #Set model hyperparameters
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(10)
    ])

In [ ]:
model3.compile(optimizer='adam',          #Optimize model
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model3.fit(train_images, train_labels, epochs=10)   #Fit model

Epoch 1/10
1313/1313 [==============================] - 3s 2ms/step - loss: 0.9714 - accuracy: 0.6864
Epoch 2/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.3279 - accuracy: 0.9054
Epoch 3/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2912 - accuracy: 0.9153
Epoch 4/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2630 - accuracy: 0.9199
Epoch 5/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2423 - accuracy: 0.9267
Epoch 6/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2383 - accuracy: 0.9290
Epoch 7/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2235 - accuracy: 0.9353
Epoch 8/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2140 - accuracy: 0.9369
Epoch 9/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2080 - accuracy: 0.9383
Epoch 10/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.200

I evaluate the training set accuracy. The model uses 2 seconds of processing time with an accuracy of 0.9459.

In [ ]:
model3.evaluate(train_images, train_labels)

1313/1313 [==============================] - 2s 1ms/step - loss: 0.1832 - accuracy: 0.9459


[0.1831730306148529, 0.9458571672439575]

In [ ]:
probability_model3 = tf.keras.Sequential([model3,     #Apply softmax layer
                                         tf.keras.layers.Softmax()])

In [ ]:
predictions3 = probability_model3.predict(test_images)    #Generate test predictions

In [ ]:
index_array3 = np.argmax(predictions3, axis=-1) #I obtain my predictions in the form of an array
index_array3

array([2, 0, 9, ..., 3, 9, 2])

In [ ]:
tfpred3 = pd.DataFrame(index=df2.index) #I create a df with predictions and format for Kaggle submission
tfpred3['ImageId'] = tfpred3.index
tfpred3['ImageId'] += 1
tfpred3['Label'] = index_array3
tfpred3

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [ ]:
tfpred3.to_csv(r'C:\Users\Andrew\Desktop\tfpred3.csv', index = False, header=True) #I write a CSV with predictions and submit to Kaggle

The Kaggle submission receives a score of 0.92960 accuracy.

# Tensor Flow Test 4

For my fourth model, I want to use 5 layers with 20 nodes per layer. 

In [ ]:
model4 = tf.keras.Sequential([    #Set model hyperparameters
    tf.keras.layers.Dense(20, activation='relu'),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(20)
    ])

In [ ]:
model4.compile(optimizer='adam',  #Optimize model
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model4.fit(train_images, train_labels, epochs=10) #Fit model

Epoch 1/10
1313/1313 [==============================] - 3s 2ms/step - loss: 0.8080 - accuracy: 0.7569
Epoch 2/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.2392 - accuracy: 0.9278
Epoch 3/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1886 - accuracy: 0.9419
Epoch 4/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1631 - accuracy: 0.9518
Epoch 5/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1399 - accuracy: 0.9566
Epoch 6/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1352 - accuracy: 0.9573
Epoch 7/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1259 - accuracy: 0.9618
Epoch 8/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1126 - accuracy: 0.9658
Epoch 9/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.1114 - accuracy: 0.9653
Epoch 10/10
1313/1313 [==============================] - 2s 2ms/step - loss: 0.105

I evaluate the training set accuracy. The model uses 1 second of processing time with an accuracy of 0.9722.

In [ ]:
model4.evaluate(train_images, train_labels)

1313/1313 [==============================] - 1s 1ms/step - loss: 0.0891 - accuracy: 0.9722


[0.08907464146614075, 0.9721904993057251]

In [ ]:
probability_model4 = tf.keras.Sequential([model4, #Apply softmax layer
                                         tf.keras.layers.Softmax()])

In [ ]:
predictions4 = probability_model4.predict(test_images) #Generate test data predictions

In [ ]:
index_array4 = np.argmax(predictions4, axis=-1) #I obtain my predictions in the form of an array
index_array4

array([2, 0, 9, ..., 3, 9, 2])

In [ ]:
tfpred4 = pd.DataFrame(index=df2.index) #I create a df with predictions and format for Kaggle submission
tfpred4['ImageId'] = tfpred4.index
tfpred4['ImageId'] += 1
tfpred4['Label'] = index_array4
tfpred4

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      4
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [ ]:
tfpred4.to_csv(r'C:\Users\Andrew\Desktop\tfpred4.csv', index = False, header=True) #I write a CSV with predictions and submit to Kaggle.

The Kaggle submission receives a score of 0.95132 accuracy.

# Conclusion

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Table(header=dict(values=['Test Number', 'Number of Layers', 'Nodes per Layer', 'Processing Time (seconds)', 'Training Set Accuracy', 'Test Set Accuracy']),
                 cells=dict(values=[[1, 2, 3, 4], [2, 2, 5, 5], [10, 20, 10, 20], [1, 1, 2, 1], [0.9404, 0.9661, 0.9459, 0.9722], [0.92685, 0.94989, 0.92960, 0.95132]]))
                     ])
fig.show()

None of the tests appear to be particularly taxing for Google Colab as all the processing could be done in either one or two seconds. This leaves the training set and test set accuracies as the best methods with which to evaluate test hyperparameters. Moving between them, all of the tests showed a drop of about 0.02 in accuracy when comparing the training set to the test set.

The least accurate model was Test 1 with 2 layers of 10 nodes each. It demonstrated the lowest test accuracy at 0.92685. The next most accurate model would be Test 3 with 5 layers of 10 nodes each. Adding extra layers in this model slighlty bumped the test accuracy up to 0.92960. Test 2 with 2 layers of 20 nodes has an test accuracy of 0.94989. Finally, Test 4 with 5 layers of 20 nodes showed the most accuracy of all the models at 0.95132.

In conclusion, increasing the number of nodes appeared to have more of an impact on test accuracy than introducing additional layers. Comparing Tests 1 and 3, the test accuracy of the models only improves 0.00275 by increasing the layers and holding the nodes constant. Likewise, the difference between Tests 2 and 4 only increses 0.00143. On the other end, holding the number of layers constant but increasing the nodes showed an improvement in test accuracy of 0.02304 from Tests 1 to 3. A similary pattern is observed in Tests 2 and 4, where the test accuracy improves 0.02172. While increasing the number of layers and nodes both appear to be correlated to improved testing accuracy, I would recommend that an organization with limited computing resources focus on raising the number of nodes their model, as this would have the greatest impact on accuracy.